"""Durable immutable edit proposals, with atomic and non-replayable resolution.

Draft metadata never changes the editable revision or enters its undo stack. Applying
one proposal commits its ordinary edit and its terminal marker in the same transaction.
Reopening, undoing edits or retrying a lost response cannot turn that marker back into
an executable proposal.
"""

from datetime import datetime, timezone
import hashlib
import json
import re

from .store import ProjectError, RevisionConflict, UnsupportedProjectFormat, _expected_revision, _id, _text, _version
from . import archive


MAX_COMMAND_BYTES = 256 * 1024
_IMMUTABLE = ("id", "project_id", "title", "base_revision", "commands", "created_at")
_FIELDS = (*_IMMUTABLE, "status", "applied_revision", "closed_at")


def _canonical(value):
    try:
        return json.dumps(value, ensure_ascii=False, allow_nan=False, sort_keys=True, separators=(",", ":"))
    except (TypeError, ValueError, RecursionError) as exc:
        raise ProjectError(f"Expected finite JSON data: {exc}") from None


def _digest(value):
    return hashlib.sha256(_canonical(value).encode("utf-8")).hexdigest()


def _commands(store, commands, expected_revision):
    commands = store._prepare_commands(commands, expected_revision)
    try:
        size = len(_canonical(commands).encode("utf-8"))
    except UnicodeEncodeError:
        raise ProjectError("Draft commands must contain valid UTF-8 text") from None
    if size > MAX_COMMAND_BYTES:
        raise ProjectError("Draft commands exceed the 256 KiB limit")
    return commands


class Drafts:
    def __init__(self, store):
        self.store = store

    @staticmethod
    def _require(db):
        if _version(db) < 6:
            raise UnsupportedProjectFormat("Upgrade this project to format 6 before saving or reading drafts")

    def _decode(self, row):
        if row is None:
            raise ProjectError("Project draft not found")
        value = dict(row)
        try:
            _id(value["id"])
            if value["project_id"] != self.store._project_id:
                raise ValueError("project identity mismatch")
            _text(value["title"], "Draft title")
            _expected_revision(value["base_revision"])
            value["commands"] = _commands(self.store, json.loads(value["commands"]), value["base_revision"])
            # All generated object IDs must already be frozen. Never generate new ones
            # from a damaged stored draft when the user explicitly applies it later.
            for command in value["commands"]:
                if not isinstance(command, dict):
                    raise ValueError("command is not an object")
                if command.get("op") in ("create_table", "add_field", "add_record"):
                    _id(command.get("id"))
            if not isinstance(value["request_sha256"], str) or not re.fullmatch(r"[a-f0-9]{64}", value["request_sha256"]):
                raise ValueError("invalid request checksum")
            expected = _digest({key: value[key] for key in (*_IMMUTABLE, "request_sha256")})
            if expected != value["sha256"]:
                raise ValueError("identity/checksum mismatch")
            datetime.fromisoformat(value["created_at"])
            status, applied, closed = value["status"], value["applied_revision"], value["closed_at"]
            if status == "pending":
                valid = applied is None and closed is None
            elif status == "applied":
                valid = type(applied) is int and applied == value["base_revision"] + 1 and isinstance(closed, str)
            elif status == "discarded":
                valid = applied is None and isinstance(closed, str)
            else:
                valid = False
            if not valid:
                raise ValueError("invalid resolution state")
            if closed is not None:
                datetime.fromisoformat(closed)
        except (KeyError, TypeError, ValueError, RecursionError) as exc:
            raise ProjectError(f"Invalid stored project draft: {exc}") from None
        return {key: value[key] for key in _FIELDS}

    def _existing(self, db, draft_id, request_sha256):
        row = db.execute("SELECT * FROM project_drafts WHERE id=?", (draft_id,)).fetchone()
        if row is None:
            return None
        draft = self._decode(row)
        if row["request_sha256"] != request_sha256:
            raise RevisionConflict("Draft ID already belongs to a different request")
        return draft

    def save(self, commands, *, expected_revision, title, draft_id):
        """Validate by actual preview, then save without editing the project.

        The caller keeps its draft UUID across retries. Its original request digest is
        independent of any object UUIDs generated by preview, so a lost save response
        returns the same immutable draft even after the project revision advances.
        """
        _id(draft_id)
        title = _text(title, "Draft title")
        commands = _commands(self.store, commands, expected_revision)
        try:
            request_sha256 = _digest({"commands": commands, "title": title, "base_revision": expected_revision})
        except UnicodeEncodeError:
            raise ProjectError("Draft title must contain valid UTF-8 text") from None
        with self.store._connect() as db:
            self._require(db)
            existing = self._existing(db, draft_id, request_sha256)
            if existing is not None:
                return existing
            current = db.execute("SELECT revision FROM project").fetchone()[0]
            if current != expected_revision:
                raise RevisionConflict(f"Expected revision {expected_revision}, current revision is {current}")

        try:
            proposal = self.store.preview(commands, expected_revision=expected_revision)
        except RevisionConflict:
            # Another identical save may have won and already been applied between
            # our first lookup and preview. Recover its frozen IDs rather than
            # report an obsolete CAS error for a request that is already durable.
            with self.store._connect() as db:
                self._require(db)
                existing = self._existing(db, draft_id, request_sha256)
                if existing is not None:
                    return existing
            raise
        normalized = _commands(self.store, proposal["commands"], expected_revision)
        with self.store._connect(write=True) as db:
            return self._save_validated(db, normalized, expected_revision=expected_revision,
                                        title=title, draft_id=draft_id, request_sha256=request_sha256)

    def _save_validated(self, db, normalized, *, expected_revision, title, draft_id, request_sha256):
        """Save already-previewed commands within the caller's write transaction.

        The original request digest can differ from the normalized commands when
        preview generated UUIDs. Callers must preview first; this final CAS and
        insert allow a durable proposal and its provenance to commit together.
        """
        self._require(db)
        existing = self._existing(db, draft_id, request_sha256)
        if existing is not None:
            return existing
        current = db.execute("SELECT revision FROM project").fetchone()[0]
        if current != expected_revision:
            raise RevisionConflict(f"Expected revision {expected_revision}, current revision is {current}")
        draft = {"id": draft_id, "project_id": self.store._project_id, "title": title,
                 "base_revision": expected_revision, "commands": normalized,
                 "created_at": datetime.now(timezone.utc).isoformat(), "status": "pending",
                 "applied_revision": None, "closed_at": None}
        digest = _digest({**{key: draft[key] for key in _IMMUTABLE}, "request_sha256": request_sha256})
        db.execute("""INSERT INTO project_drafts
            (id, project_id, title, base_revision, commands, request_sha256, sha256, created_at,
             status, applied_revision, closed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', NULL, NULL)""",
                   (draft_id, draft["project_id"], title, expected_revision, _canonical(normalized),
                    request_sha256, digest, draft["created_at"]))
        return draft

    def get(self, draft_id):
        _id(draft_id)
        with self.store._connect() as db:
            self._require(db)
            return self._decode(db.execute("SELECT * FROM project_drafts WHERE id=?", (draft_id,)).fetchone())

    def list(self, *, offset=0, limit=100, archived=None):
        if type(offset) is not int or offset < 0 or type(limit) is not int or not 1 <= limit <= 100:
            raise ProjectError("Draft pagination requires offset >= 0 and limit between 1 and 100")
        with self.store._connect() as db:
            self._require(db)
            where, extra = archive.where(db, "draft", archived)
            rows = db.execute("SELECT * FROM project_drafts" + where + " ORDER BY rowid LIMIT ? OFFSET ?", (*extra, limit + 1, offset)).fetchall()
            drafts = [{key: value for key, value in self._decode(row).items() if key != "commands"} for row in rows[:limit]]
            return {"drafts": drafts, "next_offset": offset + limit if len(rows) > limit else None}

    def apply(self, draft_id, *, expected_revision):
        """Apply once at the frozen base; retries report the original committed revision."""
        _id(draft_id)
        _expected_revision(expected_revision)
        self.store.archive.require_active("draft", draft_id, "apply it")
        with self.store._connect(write=True) as db:
            self._require(db)
            draft = self._decode(db.execute("SELECT * FROM project_drafts WHERE id=?", (draft_id,)).fetchone())
            if expected_revision != draft["base_revision"]:
                raise RevisionConflict("Expected revision must match the saved draft's base revision")
            if draft["status"] == "applied":
                return {"draft": draft, "revision": draft["applied_revision"], "replayed": True}
            if draft["status"] == "discarded":
                raise RevisionConflict("This draft has been discarded")
            result = self.store._apply(db, draft["commands"], expected_revision)
            closed_at = datetime.now(timezone.utc).isoformat()
            db.execute("UPDATE project_drafts SET status='applied', applied_revision=?, closed_at=? WHERE id=?",
                       (result["revision"], closed_at, draft_id))
            draft.update(status="applied", applied_revision=result["revision"], closed_at=closed_at)
            return {"draft": draft, "revision": result["revision"], "replayed": False}

    def discard(self, draft_id):
        _id(draft_id)
        self.store.archive.require_active("draft", draft_id, "discard it")
        with self.store._connect(write=True) as db:
            self._require(db)
            draft = self._decode(db.execute("SELECT * FROM project_drafts WHERE id=?", (draft_id,)).fetchone())
            if draft["status"] == "applied":
                raise RevisionConflict("An applied draft cannot be discarded")
            if draft["status"] == "pending":
                closed_at = datetime.now(timezone.utc).isoformat()
                db.execute("UPDATE project_drafts SET status='discarded', closed_at=? WHERE id=?", (closed_at, draft_id))
                draft.update(status="discarded", closed_at=closed_at)
            return draft
