/* SPDX-License-Identifier: GPL-2.0-or-later */
/** \file
 * Default dark theme.
 *
 * Source: Blender 5.2.1, release/datafiles/userdef/userdef_default_theme.c (`U_theme_default`,
 * generated by tools/utils/blender_theme_as_c.py), tarball sha256
 * 14ca60236b029f575c2a8b6042554c956736206adef5ecb396445a394c0c9213 (desktop/engine/third_party/
 * blender/UPSTREAM.json). Field mapping:
 *   Theme::<widget>      <- .tui.wcol_<widget>   (outline, outline_sel, inner, inner_sel, item, text,
 *                                                  text_sel, roundness; `shaded` is 0 everywhere)
 *   Theme::state         <- .tui.wcol_state      (error, warning, info, success)
 *   widget_emboss, menu_shadow_fac/width, editor_border, text_cursor (widget_text_cursor), link,
 *   panel_*              <- .tui.<same name>
 *   region_back, space_* <- .space_properties.back/text/text_hi/title (back alpha forced to 0xff:
 *                           Blender uses the 0x00 alpha only for region overlap)
 *   header_back          <- .space_properties.header (alpha forced to 0xff)
 * Metrics (Style) follow source/blender/editors/interface/interface_style.cc (uiStyle defaults:
 * buttonspacex 8, buttonspacey 2, columnspace 8, boxspace 5, panelspace 8; widget text 11 pt) and
 * UI_interface_c.hh (UI_UNIT_X = U.widget_unit, UI_TEXT_MARGIN_X 0.4, UI_PANEL_MARGIN_X 0.4 U).
 */
#include "stk/ui/theme.hh"

#include <cmath>

namespace stk::ui {

static WidgetColors wcol(uint32_t outline,
                         uint32_t outline_sel,
                         uint32_t inner,
                         uint32_t inner_sel,
                         uint32_t item,
                         uint32_t text,
                         uint32_t text_sel,
                         float roundness)
{
  return {Color::hex(outline), Color::hex(outline_sel), Color::hex(inner), Color::hex(inner_sel),
          Color::hex(item),    Color::hex(text),        Color::hex(text_sel), roundness};
}

Theme Theme::blender_dark()
{
  Theme t;
  /*                outline     outline_sel inner       inner_sel   item        text        text_sel    round */
  t.regular = wcol(0x3d3d3dff, 0x3d3d3dff, 0x545454ff, 0x4772b3ff, 0x1d1d1d80, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.tool = wcol(0x3d3d3dff, 0x3d3d3dff, 0x545454ff, 0x4772b3ff, 0xffffffff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.text = wcol(0x3d3d3dff, 0x3d3d3dff, 0x1d1d1dff, 0x181818ff, 0xffffff33, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.option = wcol(0x3d3d3dff, 0x3d3d3dff, 0x545454ff, 0x4772b3ff, 0xffffffff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.toggle = wcol(0x3d3d3dff, 0x3d3d3dff, 0x545454ff, 0x4772b3ff, 0x252525ff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.num = wcol(0x3d3d3dff, 0x3d3d3dff, 0x545454ff, 0x222222ff, 0x4772b3ff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.numslider = wcol(0x3d3d3dff, 0x3d3d3dff, 0x545454ff, 0x222222ff, 0x4772b3ff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.tab = wcol(0x1d1d1dff, 0x1d1d1dff, 0x1d1d1dff, 0x303030ff, 0x1d1d1dff, 0x989898ff, 0xffffffff, 0.2f);
  t.menu = wcol(0x3d3d3dff, 0x3d3d3dff, 0x282828ff, 0x4772b3b3, 0xd9d9d9ff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.pulldown = wcol(0x3d3d3d00, 0x3d3d3d00, 0x22222200, 0xffffff1a, 0xffffff8f, 0xd9d9d9ff, 0xffffffff, 0.2f);
  t.menu_back = wcol(0x242424ff, 0x242424ff, 0x181818ff, 0x4772b3ff, 0xd9d9d9ff, 0x999999ff, 0xffffffff, 0.2f);
  t.menu_item = wcol(0x3d3d3d00, 0x3d3d3d00, 0x18181800, 0x4772b3ff, 0xffffff8f, 0xddddddff, 0xffffffff, 0.2f);
  t.tooltip = wcol(0x242424ff, 0x242424ff, 0x1d1d1dff, 0x4772b3ff, 0xd9d9d9ff, 0xd9d9d9ff, 0xffffffff, 0.2f);
  t.box = wcol(0x3d3d3dff, 0x3d3d3dff, 0x1d1d1d80, 0x545454ff, 0x191919ff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.scroll = wcol(0x3d3d3dff, 0x3d3d3dff, 0x22222200, 0xffffffff, 0x545454ff, 0xe6e6e6ff, 0xffffffff, 0.5f);
  t.progress = wcol(0x3d3d3dff, 0x3d3d3dff, 0x222222ff, 0x4772b3ff, 0x4772b3ff, 0xe6e6e6ff, 0xffffffff, 0.2f);
  t.list_item = wcol(0x2d2d2d00, 0x2d2d2dff, 0xffffff00, 0x4772b3ff, 0xffffff33, 0xccccccff, 0xffffffff, 0.2f);

  t.state.error = Color::hex(0x991616ff);
  t.state.warning = Color::hex(0xac8737ff);
  t.state.info = Color::hex(0x28487dff);
  t.state.success = Color::hex(0x188625ff);

  t.widget_emboss = Color::hex(0x00000026);
  t.menu_shadow_fac = 0.2f;
  t.menu_shadow_width = 6.0f;
  t.editor_border = Color::hex(0x161616ff);
  t.text_cursor = Color::hex(0x71a8ffff);
  t.link = Color::hex(0x6fa9e6ff);

  t.panel_roundness = 0.4f;
  t.panel_header = Color::hex(0x3d3d3dff);
  t.panel_back = Color::hex(0x3d3d3dff);
  t.panel_sub_back = Color::hex(0x0000001f);
  t.panel_outline = Color::hex(0xffffff11);
  t.panel_title = Color::hex(0xe6e6e6ff);
  t.panel_text = Color::hex(0xe6e6e6ff);

  t.region_back = Color::hex(0x303030ff);
  t.header_back = Color::hex(0x303030ff);
  t.space_text = Color::hex(0xe6e6e6ff);
  t.space_text_hi = Color::hex(0xffffffff);
  t.space_title = Color::hex(0xe6e6e6ff);
  t.modal_dim = Color::hex(0x00000059);
  return t;
}

Style Style::from_scale(float scale)
{
  Style s;
  s.scale = scale;
  /* WM_window_dpi_set_userdef(): pixelsize = max(1, int(scale)), widget_unit = round(18 * scale)
   * + 2 * pixelsize. */
  s.pixel = std::max(1.0f, std::floor(scale));
  s.unit = std::round(18.0f * scale) + 2.0f * s.pixel;
  s.font = {FontKind::Regular, std::round(11.0f * scale * 4.0f) / 4.0f};
  s.mono = {FontKind::Mono, std::round(11.0f * scale * 4.0f) / 4.0f};
  s.space_x = std::round(8.0f * scale);
  s.space_y = std::round(2.0f * scale);
  s.column_space = std::round(8.0f * scale);
  s.box_space = std::round(5.0f * scale);
  s.text_margin = std::round(0.4f * s.unit);
  s.panel_margin = std::round(0.4f * s.unit);
  s.panel_space = std::round(8.0f * scale);
  s.panel_header = std::round(1.2f * s.unit);
  s.line_height = std::round(s.font.size_px * 1.45f);
  s.scrollbar = std::round(0.35f * s.unit);
  return s;
}

float Style::u(float units) const
{
  return std::round(units * unit);
}

}  // namespace stk::ui
