// The web decoder, labels and camera against the Python reference (docs/specs/stk-render-payload-v2.md):
// every case of the desktop parity fixtures (desktop/tests/unit/fixtures, generated by make_fixtures.py) must get
// the Python verdict and warnings, every label the Python text and every camera the Python pose.
// STK_REPO_ROOT points at the repository when the web directory is used from elsewhere.
import {test, expect} from '@playwright/test';
import {existsSync, readFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {PayloadError, clearBlobCache, loadPayload, loadStkp, parseStkp, type LoadedPayload} from '../src/payload';
import {formatNumber, genericCategoryColor, volumeColorPoints, greyColormap} from '../src/colormaps';
import {cameraPose, presetOf} from '../src/camera';

const ROOT = process.env.STK_REPO_ROOT ?? join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const FIXTURES = join(ROOT, 'desktop', 'tests', 'unit', 'fixtures');
const EXAMPLE = join(ROOT, 'docs', 'specs', 'examples', 'payload-v2');
const haveFixtures = existsSync(join(FIXTURES, 'payload', 'cases.json'));
const fixture = (name: string) => JSON.parse(readFileSync(join(FIXTURES, name), 'utf8'));
const toArrayBuffer = (b: Uint8Array) => b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer;
const exampleFetch = async (sha: string) => toArrayBuffer(readFileSync(join(EXAMPLE, `${sha}.bin`)));
const number = (v: unknown) => (typeof v === 'string' ? ({inf: Infinity, '-inf': -Infinity, nan: NaN} as Record<string, number>)[v] : v as number);

function applyPatch(m: any, [op, path, value]: [string, (string | number)[], unknown]) {
  if (op === 'set' && path.length === 0) return structuredClone(value);
  let target = m;
  for (const key of path.slice(0, -1)) target = target[key];
  const last = path[path.length - 1];
  if (op === 'set') target[last] = structuredClone(value);
  else if (op === 'delete') { if (Array.isArray(target)) target.splice(last as number, 1); else delete target[last]; }
  else if (op === 'append') target[last].push(structuredClone(value));
  return m;
}

async function decodeCase(c: any): Promise<LoadedPayload> {
  if (c.kind === 'example') {
    let m = JSON.parse(readFileSync(join(EXAMPLE, 'manifest.json'), 'utf8'));
    for (const patch of c.patches) m = applyPatch(m, patch);
    return loadPayload(m, {fetchBlob: exampleFetch});
  }
  if (c.kind === 'blobs') return loadPayload(c.manifest, {fetchBlob: async sha => toArrayBuffer(Buffer.from(c.blobs[sha] ?? '', 'base64'))});
  if (c.kind === 'stkp_bytes') return loadStkp(toArrayBuffer(Buffer.from(c.data, 'base64')));
  let bytes = Buffer.from(readFileSync(join(EXAMPLE, 'example.stkp')));
  for (const [at, hex] of c.edits) Buffer.from(hex, 'hex').copy(bytes, at);
  if (c.truncate !== null && c.truncate !== undefined) bytes = bytes.subarray(0, c.truncate);
  if (c.append) bytes = Buffer.concat([bytes, Buffer.from(c.append, 'hex')]);
  return loadStkp(toArrayBuffer(bytes));
}

test.describe('parity with the Python reference', () => {
  test.skip(!haveFixtures, 'the desktop parity fixtures are not available');

  test('every payload case gets the Python verdict and warnings', async () => {
    clearBlobCache();
    const differ: string[] = [];
    for (const c of fixture('payload/cases.json')) {
      let ok = true, warnings: string[] = [], message = '';
      try { warnings = (await decodeCase(c)).skipped.map(w => w.path); } catch (error) {
        if (!(error instanceof PayloadError)) throw error;
        ok = false;
        message = error.problems[0];
      }
      if (ok !== c.python.ok) differ.push(`${c.name}: python ${c.python.ok ? 'accepts' : `rejects (${c.python.message})`}, web ${ok ? 'accepts' : `rejects (${message})`}`);
      else if (ok && JSON.stringify(warnings) !== JSON.stringify(c.python.warnings)) differ.push(`${c.name}: skipped ${warnings} vs ${c.python.warnings}`);
    }
    expect(differ).toEqual([]);
  });

  test('scalar-bar labels equal Python format_label', () => {
    const differ: string[] = [];
    for (const c of fixture('format_cases.json')) {
      const text = formatNumber(c.negative_zero ? -0 : number(c.value), c.format);
      if (text !== c.text) differ.push(`${JSON.stringify(c.format)} ${c.value}: ${text} vs ${c.text}`);
    }
    expect(differ).toEqual([]);
  });

  test('camera poses equal Python camera_pose', () => {
    for (const c of fixture('camera_cases.json').poses) {
      const p = {manifest: {render_origin: c.origin, view: c.view ?? undefined}} as unknown as LoadedPayload;
      const pose = cameraPose(p, c.bounds);
      const scale = Math.max(1, ...c.pose.position.map(Math.abs));
      pose.position.forEach((v, i) => expect(Math.abs(v - c.pose.position[i])).toBeLessThanOrEqual(1e-12 * scale));
      pose.focalPoint.forEach((v, i) => expect(Math.abs(v - c.pose.focal_point[i])).toBeLessThanOrEqual(1e-12 * scale));
      pose.viewUp.forEach((v, i) => expect(Math.abs(v - c.pose.view_up[i])).toBeLessThanOrEqual(1e-12));
      expect(Math.abs(pose.viewAngle - c.pose.view_angle_deg)).toBeLessThanOrEqual(1e-12);
      expect(pose.parallel).toBe(c.pose.parallel);
      expect(presetOf(p)).toBe(c.preset);
    }
  });

  test('stk:categorical colours equal Python for integers and non-integers', () => {
    for (const c of fixture('colormap_cases.json').categorical) {
      genericCategoryColor(c.v).forEach((v, i) => expect(Math.abs(v - c.rgb[i])).toBeLessThanOrEqual(1e-12));
    }
  });
});

test('the example decodes without warnings', async () => {
  const p = await loadStkp(toArrayBuffer(readFileSync(join(EXAMPLE, 'example.stkp'))));
  expect(p.layers.map(l => l.id)).toContain('density');
  expect(p.skipped).toEqual([]);
});

test('.stkp framing: exact length, reserved field, strict UTF-8 JSON', () => {
  const data = readFileSync(join(EXAMPLE, 'example.stkp'));
  expect(() => parseStkp(toArrayBuffer(Buffer.concat([data, Buffer.alloc(8)])))).toThrow(PayloadError);
  const reserved = Buffer.from(data);
  reserved[16 + 12] = 1;
  expect(() => parseStkp(toArrayBuffer(reserved))).toThrow(/保留字段/);
  const utf8 = Buffer.from(data);
  utf8[16 + 16 + 12] = 0xff;
  expect(() => parseStkp(toArrayBuffer(utf8))).toThrow(/UTF-8/);
});

test('labels round half to even and never print -0', () => {
  expect(formatNumber(0.125, '.2f')).toBe('0.12');
  expect(formatNumber(2.5, 'd')).toBe('2');
  expect(formatNumber(-0, '.3g')).toBe('0');
  expect(formatNumber(-0.0001, '08.2f')).toBe('00000.00');
  expect(formatNumber(1234567, ',d')).toBe('1,234,567');
  expect(formatNumber(1e16, '')).toBe('1e+16');
  expect(formatNumber(1, 'bogus')).toBe('1');
});

test('a degenerate volume range is one colour, LUT entry 128', () => {
  const grey = greyColormap();
  for (const range of [[2, 2], [3, 1]] as [number, number][]) expect(volumeColorPoints(grey, range, 'v', [])).toEqual([[range[0], 128 / 255, 128 / 255, 128 / 255]]);
  expect(volumeColorPoints(grey, [0, 1], 'v', [])).toHaveLength(256);
});
