"""Write desktop/engine/lib/stk_io/src/pyregex_tables.inc: the code points Python's re matches with
\\d, \\w and \\s in str patterns, so the C++ engine (pyregex.cc) classifies characters exactly as the
Python interpreter that validates graphs (suan.graph.schema uses re.search).

    PYTHONPATH=. python desktop/tests/unit/fixtures/make_regex_tables.py
"""
from pathlib import Path
import re
import sys
import unicodedata

ROOT = Path(__file__).resolve().parents[4]
OUT = ROOT / "desktop" / "engine" / "lib" / "stk_io" / "src" / "pyregex_tables.inc"


def ranges(pattern):
    compiled = re.compile(pattern)
    out, start = [], None
    for cp in range(0x110000):
        ok = compiled.match(chr(cp)) is not None
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, table):
    lines = [f"constexpr CodeRange {name}[] = {{"]
    row = []
    for lo, hi in table:
        row.append(f"{{0x{lo:X}, 0x{hi:X}}}")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    version = sys.version.split()[0]
    header = (
        "/* SPDX-License-Identifier: GPL-2.0-or-later */\n"
        f"/* Generated by desktop/tests/unit/fixtures/make_regex_tables.py from Python {version}\n"
        f" * (Unicode {unicodedata.unidata_version}): code points matched by re's \\d, \\w and \\s in str patterns. */\n\n"
    )
    body = "\n\n".join(emit(name, ranges(p)) for name, p in (("kDigit", r"\d"), ("kWord", r"\w"), ("kSpace", r"\s")))
    OUT.write_text(header + body + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
