name: Build pyqt app
on:  # 这里我设置了两个事件，一般的push tag以v开头，用来测试发布，而release用来正式发布
  release:
    types: [published]
  push:
      # 匹配特定标签 (refs/tags)
      tags:
        - 'v*' # 推送事件匹配 v*, 例如 v1.0，v20.15.10 等来触发工作流
jobs:
    build:
      name: Build pyqt
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: build exe
        run:  |
          pyinstaller apps\template\pyqt\src\main.spec
      - name: build app
        run:  |
          