name: Deploy to Cloudflare Pages
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    paths:
      - "docs/**"
      - .github/workflows/publish_docs.yml
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write
jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:

      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd docs
          nvm use 18
          npm install
          npm run build

      - name: Publish
        run: |
          export CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }}
          export CLOUDFLARE_ACCOUNT_ID=${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          cd docs
          nvm use 18
          npm run deploy
